### ISSUE TITLE
How can I add new commands/sensors to devices?

### ISSUE THREAD

**Issue by pickonedev** [zhbjsh/homeassistant-ssh#17]
Hi!

The addon it is working very well. Congrats for your work.
I have a question about temperature sensors, can I add more commands to a device? 
I saw that you can configure the device and all the commands/sensors are there, still... how can I add something like this?

If I add this:
```
- command: sensors | grep -A 0 'Sensor 1:' | cut -c16-19
  scan_inerval: 30
  sensors:
    - type: number
      name: CPU Temperature
      key: cpu_temperature
      unit_of_measurement: °C
```

I get this error: extra keys not allowed @ data['sensor_commands']['scan_inerval']

Thank you in advance!
