### ISSUE TITLE
Help adding a Vodafone router

### ISSUE THREAD

**Issue by cvc90** [zhbjsh/homeassistant-ssh#19]
Hi @zhbjsh,

I can't add integration with a Vodafone router through its SSH connection, the router doesn't have the commands to filter the result such as "sed, grep, cat, awk, etc..."

The command I run is the following and its response

view @ VFH-ROUTER> show interface wifi status
Wifi Status : Up

How could I add this as a binary sensor, to know if the router's WiFi is on?

**Comment by zhbjsh** [comment]
Hi! You can try the following configuration:

```
- command: show interface wifi status
  sensors:
    - type: binary
      name: Wifi status
      payload_on: "Wifi Status : Up"
```

Hope this solution works for you!
