### ISSUE TITLE
Update entity

### ISSUE THREAD

**Issue by felipecrs** [zhbjsh/homeassistant-ssh#25]
Imagine how awesome it would be if I could provide a command that checks for updates like `apt list --upgradable 2>/dev/null | grep -v "Listing"` and another one to apply the updates, like `sudo apt upgrade -y`, and there was an entity in Home Assistant so that I can trigger the updates from there?

My intention is not to actually use this with `apt`, but if available, I believe I can write automation to check if there is any update for my OpenWRT routers, and even apply it in a button.

**Comment by zhbjsh** [comment]
Hi! Thanks, this is actually a good idea, if I have time I will try to implement this in a future version! Just a binary sensor to check for updates plus a command to trigger the update seems to be quite simple, but for a good update entity we would probably need at least two more sensors to get installed version/latest version. Anyway, I will see what I can do!

**Comment by zhbjsh** [comment]
I added a new `version` sensor type to create update entities, see the example [here](https://github.com/zhbjsh/homeassistant-ssh#package-version). The two sensors can also be in different commands of course. Make sure to set an appropriate `timeout_set` if the update process is expected to take longer then the command timeout of your device.

**Comment by felipecrs** [comment]
Awesome, it works like a charm!

https://github.com/user-attachments/assets/6d82d3de-a53a-470a-881f-ad95700a8df3

```yaml
- command: |-
    set -e
    sudo apt-get update -qq >/dev/null
    pkgs="$(apt list --upgradable -qq 2>/dev/null | wc -l)"
    if [ "$pkgs" -eq 0 ]; then
      echo "All packages upgraded"
    else
      echo "$pkgs packages upgradable"
    fi
    echo "All packages upgraded"
  scan_interval: 86400
  sensors:
    - type: version
      name: APT
      command_set: sudo apt-get upgrade -qq
      timeout_set: 300
      latest: apt_latest
    - type: version
      name: APT latest
      key: apt_latest
```

**Comment by zhbjsh** [comment]
Nice! It is even possible to track and upgrade all installed packages individually using dynamic sensors. I came up with the following command, but I like your solution, as it doesn't create hundreds of new entities...

```yaml
- command: sudo apt-get update >/dev/null 2>&1 && apt-cache policy $(dpkg -l | awk '/^ii/ {print $2}') | awk '/^[^[:space:]]*:$/ {sub(/:.*/, "", $1); a=$1; n=NR} NR==n+1 {b=$2} NR==n+2 {print a" "b" "$2}'
  scan_interval: 86400
  sensors:
    - type: version
      name: Package
      dynamic: true
      latest: package_latest
      command_set: sudo apt-get install @{id}=@{value} -y
      timeout_set: 300
    - type: version
      name: Package latest
      key: package_latest
      dynamic: true
```
