### ISSUE TITLE
Have trouble control led light

### ISSUE THREAD

**Issue by iwinstar** [zhbjsh/homeassistant-ssh#44]
Hello, Thank you for providing such powerful integration. It's very convenient to control my OpenWRT router. But when I try to use such sensor commands to control led light. It doesn't work.

```yaml
- command: cat /sys/class/leds/green:status/brightness
  scan_interval: 60
  sensors:
    - type: binary
      name: LED
      icon: mdi:led-on
      command_on: echo 1 > /sys/class/leds/green:status/brightness
      command_off: echo 0 > /sys/class/leds/green:status/brightness
      payload_on: "0"
```
But it works fine on `SSH: Execute command`, Execute response:
```yaml
results:
  - device_id: fd0c9e917bd0d77649665f3b8a02c498
    device_name: OpenWRT
    success: true
    command: echo 1 > /sys/class/leds/green:status/brightness
    stdout: []
    stderr: []
    code: 0
```
Thanks.
