### ISSUE TITLE
No longer able to pull data from OpenWRT

### ISSUE THREAD

**Issue by felipecrs** [zhbjsh/homeassistant-ssh#56]
With the commands before 1.3.0, everything worked fine. After upgrading and resetting commands, this is how it shows up:

![Image](https://github.com/user-attachments/assets/b0f99750-4176-4c78-b619-69522454326c)

This is what I found in logs:

```
2025-05-29 14:55:44.171 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): x=$(/sbin/ip route show default 2>/dev/null) && awk '{print $5}' <<<$x || x=$(/sbin/route -n 2>/dev/null) && awk '/^0.0.0.0/ {print $NF}' <<<$x => [], ['sh: syntax error: unexpected redirection'], 2
2025-05-29 14:55:44.171 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): network_interface => None
2025-05-29 14:55:44.172 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): cat /sys/class/net/&{network_interface}/address => Execution failed (Value of required sensor network_interface is None)
2025-05-29 14:55:44.172 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): mac_address => None
2025-05-29 14:55:44.227 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): x=$(/sbin/ip route show default 2>/dev/null) && awk '{print $5}' <<<$x || x=$(/sbin/route -n 2>/dev/null) && awk '/^0.0.0.0/ {print $NF}' <<<$x => [], ['sh: syntax error: unexpected redirection'], 2
2025-05-29 14:55:44.227 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): network_interface => None
2025-05-29 14:55:44.227 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): cat /sys/class/net/&{network_interface}/device/power/wakeup => Execution failed (Value of required sensor network_interface is None)
2025-05-29 14:55:44.227 DEBUG (MainThread) [custom_components.ssh] Camera do portão (SSH): wake_on_lan => None
2025-05-29 14:55:44.227 DEBUG (MainThread) [custom_components.ssh] Finished fetching Camera do portão (SSH) state data in 0.081 seconds (success: True)
```

Note that OpenWRT uses Busybox.

**Comment by felipecrs** [comment]
@zhbjsh:

```console
$ docker run --rm -it busybox

$ cat <<<"felipe"
-sh: syntax error: unexpected redirection

$ echo "felipe" | cat
felipe
```

**Comment by zhbjsh** [comment]
Yea, looks like we need to find another solution to the problem I was trying to fix... 

My Idea was, that commands should always return an error code if they fail, which is not the case when using pipes.

**Comment by felipecrs** [comment]
Depending on the command, adding a `| grep .` at the end may suffice.

```console
$ non-existing-command | sed s/something/else/g | grep .

$ echo $?
1
```

Another idea is to store results in variables:

```console
$ output=$(non-existing-command) && echo "${output}" | sed s/something/else/g
```

This would have failed in the `output=$(non-existing-command)` command and would not execute the next one, also, `echo ${var}` would never fail, thus there is no risk in using pipes for it.

**Comment by zhbjsh** [comment]
Thanks for the ideas man! I quite like the second one, let me do some tests.... Probably I can release a fixed version on the weekend.

**Comment by felipecrs** [comment]
Happy to help! And do let me know if I can help you further.

**Comment by zhbjsh** [comment]
If you have time, copy paste this into your configuration and let me know if there are any problems!

```yaml
- command: >-
    x=$(/sbin/ip route show default 2>/dev/null) && echo "$x" | awk '{print $5}' || x=$(/sbin/route -n 2>/dev/null) && echo "$x" | awk '/^0.0.0.0/ {print $NF}'
  sensors:
    - type: text
      name: Network interface
      key: network_interface
- command: cat /sys/class/net/&{network_interface}/address
  sensors:
    - type: text
      name: MAC address
      key: mac_address
- command: cat /sys/class/net/&{network_interface}/device/power/wakeup
  sensors:
    - type: binary
      name: Wake on LAN
      key: wake_on_lan
- command: uname -n
  sensors:
    - type: text
      name: Hostname
      key: hostname
- command: uname -m
  sensors:
    - type: text
      name: Machine type
      key: machine_type
- command: uname -s
  sensors:
    - type: text
      name: OS name
      key: os_name
- command: uname -r
  sensors:
    - type: text
      name: OS version
      key: os_version
- command: (. /etc/os-release && echo "$PRETTY_NAME")
  sensors:
    - type: text
      name: OS release
      key: os_release
- command: >-
    x=$(/sbin/dmidecode -t system 2>/dev/null) && echo "$x" | awk -F ": " '/Product Name:/ {a=$2} /Version:/ {b=$2} /Manufacturer:/ {c=$2} /Serial Number:/ {d=$2} END {print a"\n"b"\n"c"\n"d}'
  sensors:
    - type: text
      name: Device name
      key: device_name
    - type: text
      name: Device model
      key: device_model
    - type: text
      name: Manufacturer
      key: manufacturer
    - type: text
      name: Serial number
      key: serial_number
- command: >-
    cat /proc/cpuinfo | awk -F ": " '/^model name/ {a=$2} /^processor/ {b=$2+1} /^Hardware/ {c=$2} /^Model/ {d=$2} END {print a"\n"b"\n"c"\n"d}'
  sensors:
    - type: text
      name: CPU name
      key: cpu_name
    - type: number
      name: CPU cores
      key: cpu_cores
    - type: text
      name: CPU hardware
      key: cpu_hardware
    - type: text
      name: CPU model
      key: cpu_model
- command: cat /proc/meminfo | awk '/MemTotal/ {print $2}'
  sensors:
    - type: number
      name: Total memory
      key: total_memory
      unit_of_measurement: KiB
- command: cat /proc/meminfo | awk '/MemFree/ {print $2}'
  scan_interval: 30
  sensors:
    - type: number
      name: Free memory
      key: free_memory
      unit_of_measurement: KiB
- command: >-
    x=$(df -k) && echo "$x" | awk '/^\/dev\// {b=$4; $1=$2=$3=$4=$5=""; gsub(/^ +/, ""); print $0"|"b}'
  scan_interval: 60
  separator: "|"
  sensors:
    - type: number
      name: Free disk space
      key: free_disk_space
      dynamic: true
      unit_of_measurement: KiB
- command: >-
    x=$(vmstat 1 2) && y=$(echo "$x" | awk 'END {print $15}') && echo $((100-$y))
  scan_interval: 30
  sensors:
    - type: number
      name: CPU load
      key: cpu_load
      unit_of_measurement: "%"
- command: >-
    for x in $(ls -d /sys/class/thermal/thermal_zone*); do echo $(cat $x/type),$(($(cat $x/temp)/1000)); done
  scan_interval: 60
  separator: ","
  sensors:
    - type: number
      name: Temperature
      key: temperature
      dynamic: true
      unit_of_measurement: °C
- command: x=$(ps -e) && echo "$x" | awk 'END {print NR-1}'
  scan_interval: 60
  sensors:
    - type: number
      name: Processes
      key: processes
```

**Comment by felipecrs** [comment]
@zhbjsh the syntax work!

![Image](https://github.com/user-attachments/assets/195de878-bd0e-4776-9be8-e1ae1b1dd596)

But there are a few compatibility issues still:

```console
root@roteador-do-escritorio:~# vmstat
-ash: vmstat: not found

root@roteador-do-escritorio:~# ps -e
ps: unrecognized option: e
BusyBox v1.36.1 (2025-04-13 16:38:32 UTC) multi-call binary.

Usage: ps

Show list of processes

        w       Wide output
```

**Comment by felipecrs** [comment]
For the CPU, you can probably use `top` if `vmstat` is not available.

For counting the processes, how about:

```bash
ls -d /proc/[0-9]* | wc -l
```

Example:

```console
root@camera-do-portao ~# ps | awk 'END {print NR-1}'
49
root@camera-do-portao ~# ls -d /proc/[0-9]* | wc -l
49
```

In my Ubuntu VM:

```console
❯ ps -e | awk 'END {print NR-1}'
175
❯ ls -d /proc/[0-9]* | wc -l
175
```

**Comment by felipecrs** [comment]
Actually, for CPU, how about:

```bash
grep 'cpu ' /proc/stat | awk '{print ($2+$4)*100/($2+$3+$4+$5)}'
```

It seems to work in all my tests.

In fact, I was unable to get accurate results when using `vmstat` even in my Ubuntu VM.

**Comment by felipecrs** [comment]
You can also simplify the thermal one:

```bash
for d in /sys/class/thermal/thermal_zone*; do echo "$(cat $d/type),$(($(cat $d/temp)/1000))"; done
```

(there's no need for `ls`)

**Comment by felipecrs** [comment]
FYI I was able to extract some information from OpenWRT with this:

```
~ ❯ ssh root@192.168.1.1 cat /proc/device-tree/model                                                                                                                                18:34:27
Xiaomi Mi Router AX3000T (OpenWrt U-Boot layout)

~ ❯ ssh root@192.168.1.1 cat /proc/device-tree/compatible                                                                                                                           18:34:18
xiaomi,mi-router-ax3000t-ubootmod
```

`dmidecode` is not available there. Funny because it's also not available in my Ubuntu VM. But in my Ubuntu VM, neither `/proc/device-tree` is (maybe because it is a VM). Could you give it a try too?

**Comment by felipecrs** [comment]
> For the CPU, you can probably use `top` if `vmstat` is not available.
> 
> For counting the processes, how about:
> 
> ls -d /proc/[0-9]* | wc -l
> Example:
> 
> root@camera-do-portao ~# ps | awk 'END {print NR-1}'
> 49
> root@camera-do-portao ~# ls -d /proc/[0-9]* | wc -l
> 49
> In my Ubuntu VM:
> 
> ❯ ps -e | awk 'END {print NR-1}'
> 175
> ❯ ls -d /proc/[0-9]* | wc -l
> 175

Here is better optimized version:

```bash
printf '%s\n' /proc/[0-9]* | wc -l
```

**Comment by zhbjsh** [comment]
> Actually, for CPU, how about:
> 
> grep 'cpu ' /proc/stat | awk '{print ($2+$4)*100/($2+$3+$4+$5)}'
> 
> It seems to work in all my tests.
> 
> In fact, I was unable to get accurate results when using `vmstat` even in my Ubuntu VM.

@felipecrs  As I understand it, the values in `/proc/stat` should be compared after some time has passed, otherwise you just get the average CPU usage. I found this example [here](https://www.idnt.net/en-GB/kb/941772) which I modified a bit to make it as short as possible. What do you think?

```yaml
- command: |-
    for i in 1 2; do
      x2=($(head -n1 /proc/stat)) 
      sum2="${x2[@]:1}" 
      sum2=$((${sum2// /+}))
      if [[ $i == 1 ]]; then
        x1=("${x2[@]}") 
        sum1=$sum2
        sleep 1 
      fi
    done
    d=$((sum2-sum1)) 
    echo $((100*$((d-$((x2[4]-x1[4]))))/d))
  scan_interval: 30
  sensors:
    - type: number
      name: CPU load
      key: cpu_load
      unit_of_measurement: "%"
```

**Comment by zhbjsh** [comment]
> You can also simplify the thermal one:
> 
> for d in /sys/class/thermal/thermal_zone*; do echo "$(cat $d/type),$(($(cat $d/temp)/1000))"; done
> 
> (there's no need for `ls`)

Thanks, didn't see that!

**Comment by zhbjsh** [comment]
Also this one is great, will use it from now on!

```
printf '%s\n' /proc/[0-9]* | wc -l
```

**Comment by felipecrs** [comment]
> [@felipecrs](https://github.com/felipecrs) As I understand it, the values in `/proc/stat` should be compared after some time has passed, otherwise you just get the average CPU usage. I found this example [here](https://www.idnt.net/en-GB/kb/941772) which I modified a bit to make it as short as possible. What do you think?
> 
> - command: |-
>     for i in 1 2; do
>       x2=($(head -n1 /proc/stat)) 
>       sum2="${x2[@]:1}" 
>       sum2=$((${sum2// /+}))
>       if [[ $i == 1 ]]; then
>         x1=("${x2[@]}") 
>         sum1=$sum2
>         sleep 1 
>       fi
>     done
>     d=$((sum2-sum1)) 
>     echo $((100*$((d-$((x2[4]-x1[4]))))/d))
>   scan_interval: 30
>   sensors:
>     - type: number
>       name: CPU load
>       key: cpu_load
>       unit_of_measurement: "%"

Sorry @zhbjsh, you are totally right, and I completely underestimated this. Unfortunately, I don't think this is working as expected either.

The results seem nowhere like `top`, at least for me:

https://github.com/user-attachments/assets/d28dd88f-cdf2-43fe-ac0d-f72845460272

I think the safest option is to still use `top` or `vmstat` depending on which one is available.

But I'm honestly not sure. :(

**Comment by felipecrs** [comment]
In case you think it's a good idea, I made this command which works for both my OpenWRT devices and my Ubuntu VM:

```bash
top -bn1 | grep -m1 -oE '^(%Cpu\(s\)|CPU): *[0-9]+(\.[0-9]+)?' | awk '{ print $2 }'
```

**Comment by zhbjsh** [comment]
I also just compared `top -d1`,  `/proc/stat` and `vmstat` the values seem to be quite similar on my Ubuntu laptop...

https://github.com/user-attachments/assets/783f0199-f71b-4535-b05c-cb19e8b3f8cd

**Comment by zhbjsh** [comment]
Somehow I would prefer to read from `/proc/stat`, as it would work on most machines, independent from `top` (which has many different versions) or `vmstat` (which might be not available)

**Comment by felipecrs** [comment]
> I also just compared `top -d1`, `/proc/stat` and `vmstat` the values seem to be quite similar on my Ubuntu laptop...
> 
>  Screencast.from.2025-06-02.13-53-03.webm

Oh. In `top` I must sum both the `usr` and `sys` consumptions to get the overall CPU usage (or subtract `idle` from 100 as you hinted). That's why my results were being different.

Alright, I agree now that reading from `/proc/stat` is the best. I changed your script so that it can work in busybox/POSIX too:

```bash
read _ u n s i _ < /proc/stat
t1=$((u+n+s+i))
sleep 1
read _ u2 n2 s2 i2 _ < /proc/stat
t2=$((u2+n2+s2+i2))
echo $((100 * ((t2 - t1) - (i2 - i)) / (t2 - t1)))
```

**Comment by tryingbe** [comment]
Will there be an update to SSH when this is fixed?

**Comment by zhbjsh** [comment]
@felipecrs Thanks, that looks a lot cleaner then my CPU script! Didn't have time to test it yet, but will do so the next days and then release the new version @tryingbe

**Comment by zhbjsh** [comment]
@felipecrs I added some more columns from `/proc/stat` to match the answer of [this post](https://stackoverflow.com/questions/23367857/accurate-calculation-of-cpu-usage-given-in-percentage-in-linux):

```shell
read _ u n s i w q o t _ < /proc/stat
i1=$((i+w))
t1=$((u+n+s+q+o+t+i1))
sleep 1
read _ u n s i w q o t _ < /proc/stat
i2=$((i+w))
t2=$((u+n+s+q+o+t+i2))
id=$((i2-i1))
td=$((t2-t1))
echo $((100*(td-id)/td))
```

If something doesn't work, let me know, otherwise I will use it like this. Thanks for the help!

**Comment by felipecrs** [comment]
> [@felipecrs](https://github.com/felipecrs) I added some more columns from `/proc/stat` to match the answer of [this post](https://stackoverflow.com/questions/23367857/accurate-calculation-of-cpu-usage-given-in-percentage-in-linux):
> 
> read _ u n s i w q o t _ < /proc/stat
> i1=$((i+w))
> t1=$((u+n+s+q+o+t+i1))
> sleep 1
> read _ u n s i w q o t _ < /proc/stat
> i2=$((i+w))
> t2=$((u+n+s+q+o+t+i2))
> id=$((i2-i1))
> td=$((t2-t1))
> echo $((100*(td-id)/td))
> If something doesn't work, let me know, otherwise I will use it like this. Thanks for the help!

This seems to be working great for me!

**Comment by zhbjsh** [comment]
New version is out

**Comment by felipecrs** [comment]
@zhbjsh it's working like a charm!

---

If I may ask an unrelated question...

These sensors are not supported in OpenWRT:

```yaml
- command: >-
    x=$(/sbin/dmidecode -t system 2>/dev/null) && echo "$x" | awk -F ": "
    '/Product Name:/ {a=$2} /Version:/ {b=$2} /Manufacturer:/ {c=$2} /Serial
    Number:/ {d=$2} END {print a"\n"b"\n"c"\n"d}'
  sensors:
    - type: text
      name: Device name
      key: device_name
    - type: text
      name: Device model
      key: device_model
    - type: text
      name: Manufacturer
      key: manufacturer
    - type: text
      name: Serial number
      key: serial_number
- command: >-
    cat /proc/cpuinfo | awk -F ": " '/^model name/ {a=$2} /^processor/ {b=$2+1}
    /^Hardware/ {c=$2} /^Model/ {d=$2} END {print a"\n"b"\n"c"\n"d}'
  sensors:
    - type: text
      name: CPU name
      key: cpu_name
    - type: number
      name: CPU cores
      key: cpu_cores
    - type: text
      name: CPU hardware
      key: cpu_hardware
    - type: text
      name: CPU model
      key: cpu_model
```

However, their entities seem to come **disabled by default**. Will the integration keep attempting to run these commands even if their entities are disabled, or should I get rid of these default commands from my device config to make sure the integration won't run them?
