### ISSUE TITLE
Help w/ fundamental misunderstanding of how integration is supposed to be used

### ISSUE THREAD

**Issue by johntdyer** [zhbjsh/homeassistant-ssh#65]
I thiunk I have a fundamental missunderstand iof how this is supposed to be used...  I have created a device under the integration pane and I can run a command 

```
data:
  command: ubnt-device-info firmware detail
  
response_variable: output
target:
  device_id: 845c04cb663aca6fa5162023d32890aa
enabled: true
action: ssh.execute_command

```

output

```
results:
  - device_id: 845c04cb663aca6fa5162023d32890aa
    device_name: Unifi Router
    success: true
    command: ubnt-device-info firmware detail
    stdout: []
    stderr: []
    code: 0
```

Few things that are not clear... first off why is stdout and or stderr empty in this case?  

All the examples in the docs seem partial or incomplete... I see no FULL examples of how to create sensors and or use in automations..

For [example](https://github.com/zhbjsh/homeassistant-ssh?tab=readme-ov-file#number-of-logged-in-users).  where is this defined, is it under what domain within home assistant?  Is this part of the automation or action service call ? 

All i am trying to do here is to run `ubnt-device-info firmware detail` via ssh and get that number as a sensor value.  Can you provide a complete example of how I would do this given my starting point of having just the integration created 

<img width="446" alt="Image" src="https://github.com/user-attachments/assets/395d6f0e-fc53-4f10-994d-762d4d8d2a3c" />

<img width="1357" alt="Image" src="https://github.com/user-attachments/assets/39ee137c-11f3-4dff-8b50-158c1f2c95ea" />

Maybe that will help me get over the hump , because right now I am just confused and feel like I am missing something fundamental

**Comment by zhbjsh** [comment]
Hi! Thanks for the feedback. To create a new sensor, you can copy the following code into the sensor commands field in your configuration (scan interval 24h):

```yaml
- command: ubnt-device-info firmware detail
  scan_interval: 86400
  sensors:
    - type: text
      name: Firmware
```

As your command currently doesn't return any output, you can try to enable the _Invoke shell_ option (click on the three dots next to your device and then _Reconfigure_). This should give you the same output as when you execute the command manually in a terminal.

Let me know if it works!
