### ISSUE TITLE
[Feedback] Network throughput monitoring

### ISSUE THREAD

**Issue by Bluscream** [zhbjsh/homeassistant-ssh#67]
```yaml
- command: sar -n DEV 1 1 | grep " eth0" | grep "Average:" | awk '{print $5}'
  sensors:
    - type: number
      name: Network eth0 Recieving
      key: rx_kBps_eth0
      unit_of_measurement: kB/s
- command: sar -n DEV 1 1 | grep " wlan0" | grep "Average:" | awk '{print $5}'
  sensors:
    - type: number
      name: Network wlan0 Recieving
      key: rx_kBps_wlan0
      unit_of_measurement: kB/s
- command: sar -n DEV 1 1 | grep " eth1" | grep "Average:" | awk '{print $5}'
  sensors:
    - type: number
      name: Network eth1 Recieving
      key: rx_kBps_eth1
      unit_of_measurement: kB/s
- command: sar -n DEV 1 1 | grep " eth0" | grep "Average:" | awk '{print $6}'
  sensors:
    - type: number
      name: Network eth0 Sending
      key: tx_kBps_eth0
      unit_of_measurement: kB/s
- command: sar -n DEV 1 1 | grep " wlan0" | grep "Average:" | awk '{print $6}'
  sensors:
    - type: number
      name: Network wlan0 Sending
      key: tx_kBps_wlan0
      unit_of_measurement: kB/s
- command: sar -n DEV 1 1 | grep " eth1" | grep "Average:" | awk '{print $6}'
  sensors:
    - type: number
      name: Network eth1 Sending
      key: tx_kBps_eth1
      unit_of_measurement: kB/s

- command: "sar -n DEV 1 1 | grep 'Average: ' | awk '{sum+=$5} END{print int(sum)}'"
  sensors:
    - type: number
      name: Network Recieving
      key: rx_kBps
      unit_of_measurement: kB/s
- command: "sar -n DEV 1 1 | grep 'Average: ' | awk '{sum+=$6} END{print int(sum)}'"
  sensors:
    - type: number
      name: Network Sending
      key: tx_kBps
      unit_of_measurement: kB/s

- command: iostat -dk 1 1 | grep sd | awk '{sum+=$3} END{print int(sum)}'
  sensors:
    - type: number
      name: Drives Read Speed
      key: drive_combined_read_kBps
      unit_of_measurement: kB/s
- command: iostat -dk 1 1 | grep sd | awk '{sum+=$4} END{print int(sum)}'
  sensors:
    - type: number
      name: Drives Write Speed
      key: drive_combined_write_kBps
      unit_of_measurement: kB/s

```

Can this be improved?
