### ISSUE TITLE
no sensor value for 'docker info'

### ISSUE THREAD

**Issue by MiRen76** [zhbjsh/homeassistant-ssh#7]
I never get a sensor info if I try to request the following as commands. 

- docker info -f '{{.ContainersStopped}}'
- docker info -f '{{.ContainersRunning}}'
- docker info -f '{{.ContainersPaused}}'
- docker info -f '{{.Containers}}'

I tried the commands via ssh with the user on the machine directly and it worked.

I added the follwing in the config of the ssh integration:

- command: docker info -f '{{.ContainersRunning}}'
  scan_interval: 60
  sensors:
    - type: number
      name: active container
      key: active container

**Comment by zhbjsh** [comment]
Hi! The problem here is, that double curly brackets {{ ... }} are used for templates. You should be able to make it work by escaping them with backslashes:

```
- command: docker info -f \{\{.ContainersRunning\}\}
  scan_interval: 60
  sensors:
    - type: number
      name: Active containers 
```

Hope this will help you!
