### ISSUE TITLE
Invalid JSON output

### ISSUE THREAD

**Issue by teymur1988** [zhbjsh/homeassistant-ssh#8]
Hi there, 

Thanks for the integration. I'm facing the following issue where the output from the script run on a remote server provides invalid JSON output:

```yaml
alias: Test service response parsing
sequence:
  - service: ssh.execute_command
    metadata: {}
    data:
      command: /jffs/scripts/update-trustedwanips.sh
    response_variable: output
    target:
      device_id: 5ed148cba9197da009f9966b31d06d31
    enabled: true
  - service: persistent_notification.create
    metadata: {}
    data:
      message: "{{ output }}"
mode: single

```

The output provided:

`
{'results': [{'device_id': '5ed148cba9197da009f9966b31d06d31', 'device_name': 'RT-AC3200', 'success': True, 'command': '/jffs/scripts/update-trustedwanips.sh', 'stdout': ['Name: trustedwanips', 'Type: hash:net', 'Revision: 6', 'Header: family inet hashsize 32768 maxelem 65536', 'Size in memory: 372', 'References: 4', 'Number of entries: 1', 'Members:', '182.173.67.29'], 'stderr': ['update-trustedwanips.sh: Getting latest list from Home Assistant', 'update-trustedwanips.sh: Checking the difference between the two', 'update-trustedwanips.sh: Difference found!', 'update-trustedwanips.sh: Flushing the trustedwanips ipset!', 'update-trustedwanips.sh: Added IP 182.173.67.29', 'update-trustedwanips.sh: Saving trustedwanips ipset file!'], 'code': 0}]}
`

As you can see Github marks it as invalid.

```json
{'results': [{'device_id': '5ed148cba9197da009f9966b31d06d31', 'device_name': 'RT-AC3200', 'success': True, 'command': '/jffs/scripts/update-trustedwanips.sh', 'stdout': ['Name: trustedwanips', 'Type: hash:net', 'Revision: 6', 'Header: family inet hashsize 32768 maxelem 65536', 'Size in memory: 372', 'References: 4', 'Number of entries: 1', 'Members:', '182.173.67.29'], 'stderr': ['update-trustedwanips.sh: Getting latest list from Home Assistant', 'update-trustedwanips.sh: Checking the difference between the two', 'update-trustedwanips.sh: Difference found!', 'update-trustedwanips.sh: Flushing the trustedwanips ipset!', 'update-trustedwanips.sh: Added IP 182.173.67.29', 'update-trustedwanips.sh: Saving trustedwanips ipset file!'], 'code': 0}]}
```

Could you please advise how to solve this?

**Comment by zhbjsh** [comment]
Hi, I guess that's just the way the response variable is displayed in a notification and has nothing to do with the SSH integration itself. If you just want to show some specific parts of the response, for example 'stdout', you could do it like this:

``` 
  - service: persistent_notification.create
    metadata: {}
    data:
      message: "{{ output.results[0].stdout }}"
```
